# -*- coding: utf-8 -*-
"""Generate the latest markdown report output for PPT design."""

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from multi_company import ingest_company, IndustryAggregator
from data_validator import validate_and_clean
from report_parser import parse_published_reports
from survey_parser import SurveyAggregator, SurveyReportGenerator, ingest_surveys
from yoy_comparator import YoYReportComparator


DATA_ROOT = Path(r"D:\win设备桌面\2025年业绩核算\TA效能报告\数据源\各家数据\TA 效能\TA效能数据2025")
PREV_FINAL_REPORT_PATH = Path(r"D:\win设备桌面\2025年业绩核算\TA效能报告\数据源\各家数据\医药行业TA数据服务项目报告_表格整理_修正版.xlsx")
OUT_DIR = Path(__file__).resolve().parent / "output_reports"
OUT_PATH = OUT_DIR / "TA效能_最新报告输出内容_2025问卷_for_PPT.md"


def _company_name_scale(raw: dict, fallback_name: str):
    info = raw.get("company_info", {}) if isinstance(raw, dict) else {}
    company = info.get("公司名称") or info.get("company_name") or fallback_name
    scale = info.get("公司规模分类") or info.get("公司规模") or "B"
    scale = str(scale).strip().upper()
    if scale not in ("A", "B"):
        scale = "B"
    return str(company).strip() or fallback_name, scale


def build_report():
    raw_list = []
    errors = []
    survey_agg = SurveyAggregator()

    for path in sorted(DATA_ROOT.glob("*.xlsx")):
        if path.name.startswith("~$"):
            continue
        try:
            raw = ingest_company(str(path))
            raw_list.append(raw)
            company, scale = _company_name_scale(raw, path.stem.strip())
            survey = ingest_surveys(str(path), company, scale)
            survey_agg.add_company(
                company,
                scale,
                sheet3=survey.get("sheet3"),
                sheet4=survey.get("sheet4"),
                sheet5=survey.get("sheet5"),
            )
        except Exception as exc:
            errors.append(f"{path.name}: {exc}")

    cleaned, _, validation_report = validate_and_clean(raw_list)
    curr_agg = IndustryAggregator()
    for item in cleaned:
        curr_agg.add_company(item)

    prev_paths = [str(PREV_FINAL_REPORT_PATH)]
    prev_data = parse_published_reports(prev_paths, year="2024")
    survey_sections = SurveyReportGenerator(survey_agg).generate_split_reports(
        curr_year="2025",
        prev_year="2024",
    )

    comparator = YoYReportComparator(
        curr_agg,
        prev_data,
        curr_year="2025",
        prev_year="2024",
        survey_trend_report=survey_sections,
    )
    report = comparator.generate_yoy_report()

    meta = [
        "<!--",
        "Generated by llm_wiki current report pipeline.",
        "Data basis: 2025 survey workbooks from 17 companies.",
        "Previous-year benchmark data is read directly from the final published metric workbook.",
        "Sheets 3/4/5 use 2025 survey data only.",
        "Zero values are trimmed from metrics unless explicitly meaningful.",
        "-->",
        "",
    ]
    if errors:
        meta.extend(["> 处理提示：", ""])
        for item in errors:
            meta.append(f"> - {item}")
        meta.append("")

    OUT_DIR.mkdir(exist_ok=True)
    OUT_PATH.write_text("\n".join(meta) + report, encoding="utf-8")
    return OUT_PATH, len(raw_list), len(cleaned), len(survey_agg.companies), len(errors), len(validation_report or "")


if __name__ == "__main__":
    path, raw_n, clean_n, survey_n, err_n, validation_n = build_report()
    print(path)
    print(f"raw={raw_n} cleaned={clean_n} survey={survey_n} errors={err_n} validation={validation_n}")
